"""
Physics-informed CatBoost model for the "large data" regime.

Strategy:
  - Train on REAL train_dataset.csv (150 rows) + SYNTHETIC data (thousands
    of rows) generated by numerically integrating the mechanistic PFR ODE
    fit (generate_synthetic.py / mechanistic_pfr.py) across the operating
    envelope. Synthetic rows are down-weighted relative to real rows so the
    model still anchors on ground truth, using synthetic data mainly to
    regularize the non-linear yield surface (esp. the sharp zero-yield
    cliff) between sparse real observations.
  - Same physics-engineered features as the GPR model (Da1, Da2, tau, Tavg,
    dT, selectivity ratio) so CatBoost gets the mechanistic signal directly
    as inputs, not just raw operating conditions.
  - Validated with repeated K-fold CV on REAL data only (synthetic rows are
    never used for validation, since their "truth" comes from the same
    mechanistic model being tested against -- validating on them would be
    circular).
"""
import numpy as np
import pandas as pd
from catboost import CatBoostRegressor, CatBoostClassifier, Pool
from sklearn.model_selection import RepeatedKFold

from mechanistic_pfr import predict_batch, R

MECH_PARAMS = np.load("mechanistic_params.npy")

# Same collapse threshold as the GPR pipeline: below this, the side
# reaction has consumed virtually all product B (see gpr_model.py).
COLLAPSE_THRESHOLD = 0.5


def engineer_features(df):
    log_k0_1, Ea1, log_k0_2, Ea2, log_Ua, dH1, dH2, log_rhoCp = MECH_PARAMS
    k0_1, k0_2 = np.exp(log_k0_1), np.exp(log_k0_2)

    tau = df["length_m"] / df["flow_rate_L_min"]
    Tavg = (df["inlet_temperature_K"] + df["jacket_temperature_K"]) / 2.0
    dT = df["jacket_temperature_K"] - df["inlet_temperature_K"]

    k1 = k0_1 * np.exp(-Ea1 / (R * Tavg))
    k2 = k0_2 * np.exp(-Ea2 / (R * Tavg))
    Da1 = k1 * tau
    Da2 = k2 * tau

    feats = pd.DataFrame({
        "flow_rate_L_min": df["flow_rate_L_min"],
        "concentration_mol_L": df["concentration_mol_L"],
        "inlet_temperature_K": df["inlet_temperature_K"],
        "length_m": df["length_m"],
        "jacket_temperature_K": df["jacket_temperature_K"],
        "tau": tau,
        "Tavg": Tavg,
        "dT": dT,
        "Da1": Da1,
        "Da2": Da2,
        "log_Da1": np.log1p(Da1),
        "log_Da2": np.log1p(Da2),
        "selectivity_k2_k1": k2 / k1,
    })
    return feats


def build_model():
    return CatBoostRegressor(
        iterations=2000,
        learning_rate=0.02,
        depth=5,
        l2_leaf_reg=6.0,
        loss_function="RMSE",
        early_stopping_rounds=100,
        random_seed=42,
        verbose=False,
    )


def build_classifier():
    return CatBoostClassifier(
        iterations=500,
        learning_rate=0.05,
        depth=3,
        l2_leaf_reg=6.0,
        loss_function="Logloss",
        early_stopping_rounds=50,
        random_seed=42,
        verbose=False,
    )


def two_stage_predict(X_tr_real, y_tr_real, X_tr_syn, y_tr_syn, X_test,
                        synthetic_weight=0.15):
    """Stage 1: classify collapsed (~0) vs active regime, trained on real+synthetic.
    Stage 2: regressor (real+synthetic, weighted) predicts yield, applied only
    to rows the classifier calls active. Rows called collapsed are set to 0."""
    is_active_real = (y_tr_real >= COLLAPSE_THRESHOLD).astype(int)
    is_active_syn = (y_tr_syn >= COLLAPSE_THRESHOLD).astype(int)

    X_clf_tr = pd.concat([X_tr_real, X_tr_syn], ignore_index=True)
    y_clf_tr = np.concatenate([is_active_real, is_active_syn])
    w_clf_tr = np.concatenate([
        np.ones(len(X_tr_real)), np.full(len(X_tr_syn), synthetic_weight)
    ])
    clf = build_classifier()
    clf.fit(Pool(X_clf_tr, y_clf_tr, weight=w_clf_tr), verbose=False)
    is_active_test = clf.predict(X_test).astype(bool).ravel()

    active_real_mask = is_active_real.astype(bool)
    active_syn_mask = is_active_syn.astype(bool)
    X_reg_tr = pd.concat([
        X_tr_real[active_real_mask], X_tr_syn[active_syn_mask]
    ], ignore_index=True)
    y_reg_tr = np.concatenate([
        y_tr_real[active_real_mask], y_tr_syn[active_syn_mask]
    ])
    w_reg_tr = np.concatenate([
        np.ones(active_real_mask.sum()),
        np.full(active_syn_mask.sum(), synthetic_weight),
    ])

    reg = build_model()
    reg.set_params(early_stopping_rounds=None)
    reg.fit(Pool(X_reg_tr, y_reg_tr, weight=w_reg_tr), verbose=False)

    y_pred = np.zeros(len(X_test))
    if is_active_test.any():
        y_pred[is_active_test] = np.clip(
            reg.predict(X_test[is_active_test]), 0, 100
        )
    return y_pred, is_active_test


def cross_validate_real_only(train_csv, n_splits=5, n_repeats=10):
    """CV strictly on real data to get an honest RMSE estimate."""
    df = pd.read_csv(train_csv)
    y = df["overall_yield"].values
    X = engineer_features(df)

    rkf = RepeatedKFold(n_splits=n_splits, n_repeats=n_repeats, random_state=42)
    rmses = []
    for train_idx, test_idx in rkf.split(X):
        model = build_model()
        model.fit(X.iloc[train_idx], y[train_idx],
                   eval_set=(X.iloc[test_idx], y[test_idx]),
                   use_best_model=True)
        y_pred = np.clip(model.predict(X.iloc[test_idx]), 0, 100)
        rmse = np.sqrt(np.mean((y[test_idx] - y_pred) ** 2))
        rmses.append(rmse)

    rmses = np.array(rmses)
    print(f"[Real-data-only CV] Repeated {n_splits}-fold ({n_repeats}x), n={len(rmses)} folds")
    print(f"  RMSE mean = {rmses.mean():.3f}  std = {rmses.std():.3f}")
    return rmses


def cross_validate_with_synthetic(train_csv, synthetic_csv, n_splits=5, n_repeats=10,
                                    synthetic_weight=0.15):
    """CV where each fold's train split is augmented with synthetic data
    (synthetic never enters the held-out test fold), to check that
    augmentation helps real-world generalization rather than just fitting
    the mechanistic model's own surface."""
    df_real = pd.read_csv(train_csv)
    y_real = df_real["overall_yield"].values
    X_real = engineer_features(df_real)

    df_syn = pd.read_csv(synthetic_csv)
    y_syn = df_syn["overall_yield"].values
    X_syn = engineer_features(df_syn)

    rkf = RepeatedKFold(n_splits=n_splits, n_repeats=n_repeats, random_state=42)
    rmses = []
    for train_idx, test_idx in rkf.split(X_real):
        X_tr = pd.concat([X_real.iloc[train_idx], X_syn], ignore_index=True)
        y_tr = np.concatenate([y_real[train_idx], y_syn])
        w_tr = np.concatenate([
            np.ones(len(train_idx)),
            np.full(len(X_syn), synthetic_weight),
        ])

        model = build_model()
        train_pool = Pool(X_tr, y_tr, weight=w_tr)
        test_pool = Pool(X_real.iloc[test_idx], y_real[test_idx])
        model.fit(train_pool, eval_set=test_pool, use_best_model=True)

        y_pred = np.clip(model.predict(X_real.iloc[test_idx]), 0, 100)
        rmse = np.sqrt(np.mean((y_real[test_idx] - y_pred) ** 2))
        rmses.append(rmse)

    rmses = np.array(rmses)
    print(f"[Real+Synthetic CV] Repeated {n_splits}-fold ({n_repeats}x), n={len(rmses)} folds, "
          f"synthetic_weight={synthetic_weight}")
    print(f"  RMSE mean = {rmses.mean():.3f}  std = {rmses.std():.3f}")
    return rmses


def cross_validate_two_stage(train_csv, synthetic_csv, n_splits=5, n_repeats=10,
                               synthetic_weight=0.15):
    df_real = pd.read_csv(train_csv)
    y_real = df_real["overall_yield"].values
    X_real = engineer_features(df_real)

    df_syn = pd.read_csv(synthetic_csv)
    y_syn = df_syn["overall_yield"].values
    X_syn = engineer_features(df_syn)

    rkf = RepeatedKFold(n_splits=n_splits, n_repeats=n_repeats, random_state=42)
    rmses = []
    for train_idx, test_idx in rkf.split(X_real):
        y_pred, _ = two_stage_predict(
            X_real.iloc[train_idx].reset_index(drop=True), y_real[train_idx],
            X_syn, y_syn,
            X_real.iloc[test_idx].reset_index(drop=True),
            synthetic_weight=synthetic_weight,
        )
        rmse = np.sqrt(np.mean((y_real[test_idx] - y_pred) ** 2))
        rmses.append(rmse)

    rmses = np.array(rmses)
    print(f"[Two-stage classifier+regressor, real+synthetic] Repeated {n_splits}-fold "
          f"({n_repeats}x), n={len(rmses)} folds")
    print(f"  RMSE mean = {rmses.mean():.3f}  std = {rmses.std():.3f}")
    return rmses


def fit_final_and_predict(train_csv, synthetic_csv, test_csv, out_csv,
                            synthetic_weight=0.15):
    df_real = pd.read_csv(train_csv)
    y_real = df_real["overall_yield"].values
    X_real = engineer_features(df_real)

    df_syn = pd.read_csv(synthetic_csv)
    y_syn = df_syn["overall_yield"].values
    X_syn = engineer_features(df_syn)

    df_test = pd.read_csv(test_csv)
    X_test = engineer_features(df_test)

    y_pred, is_active_test = two_stage_predict(
        X_real, y_real, X_syn, y_syn, X_test, synthetic_weight=synthetic_weight
    )

    out = pd.DataFrame({"overall_yield": np.round(y_pred, 3)})
    out.to_csv(out_csv, index=False)
    print(f"Predictions written to {out_csv}")
    print(f"Predicted active-regime rows: {is_active_test.sum()}/{len(is_active_test)}")
    return y_pred


if __name__ == "__main__":
    print("=== CV: real data only (single-stage regressor) ===")
    cross_validate_real_only("train_dataset.csv")

    print("\n=== CV: real + synthetic augmented (single-stage regressor) ===")
    cross_validate_with_synthetic("train_dataset.csv", "synthetic_dataset.csv")

    print("\n=== CV: two-stage classifier + regressor, real + synthetic ===")
    cross_validate_two_stage("train_dataset.csv", "synthetic_dataset.csv")

    print("\n=== Fitting final two-stage model, predicting test set ===")
    fit_final_and_predict("train_dataset.csv", "synthetic_dataset.csv",
                            "test_dataset.csv", "CatBoost_predictions.csv")
